const enTranslations = {
  landing_title: 'Welcome to TaskNote',
  landing_subtitle: 'Your best friend to keep up with notes and tasks!',
  landing_btn_login: 'Login',
  landing_btn_register: 'Register',
  landing_btn_english: 'English',
  landing_btn_portuguese: 'Português (BR)',
  landing_btn_spanish: 'Español',
  landing_btn_russian: 'Русский',
  landing_languages: 'You can choose one of these languages',

  password_show_txt: 'Show',
  password_hide_txt: 'Hide',
  password_helper: 'The password must be at least 8 characters long and include a number, a capital letter, and a special character',

  login_title: 'Login',
  login_email_label: 'Email',
  login_email_placeholder: 'you@example.com',
  login_password_label: 'Password',
  login_password_placeholder: 'Your password',
  login_btn_submit: 'Login',
  login_account: 'Don\'t have an account yet?',
  login_go_other: 'Create account',
  login_back_home: 'Back to home',
  login_forgot_password: 'Forgot your password?',

  register_title: 'Create account',
  register_email_label: 'Email',
  register_email_placeholder: 'you@example.com',
  register_password_label: 'Password',
  register_password_placeholder: 'Your password',
  register_password_repeat_label: 'Repeat password',
  register_btn_submit: 'Create account',
  register_account: 'Already have an account?',
  register_go_other: 'Login',
  register_back_home: 'Back to home',
  register_resent_email: 'Resend confirmation email',
  register_resent_email_secs: 'Resend in ',

  reset_title: 'Reset your password',
  reset_email_label: 'Email',
  reset_email_placeholder: 'you@example.com',
  reset_password_label: 'Password',
  reset_password_placeholder: 'Your password',
  reset_btn_submit: 'Send confirmation email',
  reset_account: 'Have you remembered your password?',
  reset_go_other: 'Login',
  reset_back_home: 'Back to home',

  complete_reset_title: 'Create your new password',
  complete_reset_password_label: 'Password',
  complete_reset_password_placeholder: 'Type your password',
  complete_reset_btn_submit: 'Reset',
  complete_reset_account: 'Have you remembered your password?',
  complete_reset_go_other: 'Login',
  complete_reset_back_home: 'Back to home',

  email_confirmation_loading: 'Confirming your email address...',
  email_confirmation_success: '✅ Email confirmed',
  email_confirmation_success_text: 'Thank you! Your email address has been successfully confirmed. You can now return to the TaskNote app and log in.',
  email_confirmation_btn: 'Login',

  home_nav_home: 'Home',
  home_nav_tasks: 'Tasks',
  home_nav_notes: 'Notes',
  home_nav_about: 'About',
  home_welcome_title: 'Hello, ',
  home_welcome_subtitle: 'Welcome to TaskNote! Get ready to complete your pending tasks',
  home_welcome_start: 'Start Your Day, Be',
  home_welcome_productive: 'Productive',
  home_input_filter: 'Filter tasks & notes',
  home_radio_everything: 'Everything',
  home_radio_tasks: 'Tasks',
  home_radio_notes: 'Notes',
  home_card_task_title: 'Tasks Summary', // remove
  home_card_task_pending: 'Pending tasks',
  home_card_task_empty: 'No pending tasks',
  home_card_task_done: 'done tasks!',
  home_completed_tasks_title: 'Completed tasks',
  home_archived_notes_title: 'Archived notes',
  home_card_task_done_empty: 'No done tasks!',
  home_card_task_btn: 'Go to Tasks',
  home_card_note_title: 'Notes Summary',
  home_card_note_count: 'Note(s)',
  home_card_note_btn: 'Go to Notes',
  home_card_search_label: 'Search tasks and notes',
  home_card_search_placeholder: 'Enter your search term...',
  home_card_search_btn: 'Search',
  home_card_search_result_label: 'Search Results',
  home_card_search_empty_result: 'No results',

  task_form_title: 'Add task',
  task_form_desc_label: 'Description',
  task_form_desc_placeholder: 'Enter the task description',
  task_form_url_label: 'URL',
  task_form_url_placeholder: 'URL (Optional)',
  task_form_duedate_label: 'Due date',
  task_form_duedate_placeholder: 'Due date (Optional)',
  task_form_submit: 'Save task',
  task_table_description: 'Description',
  task_table_done: 'Done',
  task_table_actions: 'Actions',
  task_table_action_done: 'Done',
  task_table_action_undone: 'Undone',
  task_table_action_done_yes: 'Yes',
  task_table_action_done_no: 'No',
  task_table_action_edit: 'Edit',
  task_table_action_clone: 'Clone',
  task_table_action_delete: 'Delete',
  delete_modal_title: 'Confirm deletion',
  delete_modal_body: 'Are you sure you want to delete this item? This action cannot be undone.',
  delete_modal_cancel: 'Cancel',
  delete_modal_confirm: 'Delete',

  note_form_title: 'Add note',
  note_form_title_label: 'Title',
  note_form_title_placeholder: 'Enter the note title',
  note_form_content_label: 'Note content',
  note_form_content_placeholder: 'Enter the note content',
  note_form_submit: 'Save note',
  note_table_btn_edit: 'Edit',
  note_table_btn_delete: 'Delete',
  note_action_share: 'Share',
  note_action_unshare: 'Unshare',
  note_action_copy_link: 'Copy link',
  note_action_archive: 'Archive',
  note_action_restore: 'Restore',
  note_action_delete_permanently: 'Delete permanently',

  about_page_title_one: 'About the',
  about_page_title_two: 'TaskNote App',
  about_page_title_three: 'Tasks and notes made',
  about_page_title_four: 'Easy',
  about_page_subtitle: 'Find more information about us and the app',
  about_app_title: 'About TaskNote',
  about_app_description: `TaskNote is your go-to application for managing
    tasks and notes in one convenient place. Whether you're keeping track of
    daily to-dos or organizing notes from important meetings, TaskNote helps
    you stay organized and productive.`,
  about_app_features: 'Features',
  about_app_features_one: 'Quickly add and manage tasks and notes',
  about_app_features_two: 'Search and filter notes for easy access',
  about_app_features_three: 'Intuitive and clean user interface',
  about_app_features_four: 'Dark and light theme support with responsive design',
  about_app_features_five: 'URL attachments for tasks and notes',
  about_app_features_six: 'Tagging system with multiple tags per item',
  about_app_features_seven: 'Public note sharing via public links',
  about_app_features_eight: 'Markdown formatting toolbar for rich text editing',
  about_app_features_nine: 'Email confirmation required for account security',
  about_app_help_title: 'Help & How to Use',
  about_app_help_description: `To get started, simply sign up or log in, and
    you'll have access to your personalized dashboard. From there, you can
    create, edit, and delete tasks and notes, and organize them however you
    like. Need assistance? Check out the sidebar for quick navigation.`,

  about_tech_title: 'Technology',
  about_tech_description: `TaskNote was built using modern web technologies
    that ensure speed, reliability, and security.`,
  about_tech_list_one: 'React 19 with TypeScript for the front-end',
  about_tech_list_two: 'Vite for fast builds and development',
  about_tech_list_three: 'React Router 7 for client-side routing',
  about_tech_list_four: 'i18next for internationalization support',
  about_tech_list_five: 'Bootstrap 5 for components and responsive design',
  about_tech_list_six: 'Java and Spring Boot 4.x plus GraalVM for the back-end and Cloud Native',
  about_tech_list_seven: 'PostgreSQL for database management',
  about_tech_list_eight: 'Docker for containerization and deployment',
  about_tech_list_nine: 'GitHub Actions for CI/CD, testing and linting enforcement',
  about_tech_list_ten: 'SonarCloud and GitHub QL for security and improvements checks',

  about_dev_title: 'About the Developer',
  about_dev_description: `Hi! I'm Ricardo, the developer of TaskNote. I'm
    passionate about building applications that make life easier and more
    organized. You can reach out to me at `,
  about_dev_description_two: ' for any questions or feedback.',
  about_buy_coffee_one: 'You can also ',
  about_buy_coffee_link: 'Buy me a coffee',

  account_header_my: 'My',
  account_header_account: 'Account',
  account_header_update_manage: 'Update and Manage, Your',
  account_header_data: 'Data',
  account_data_update_header: 'Update only what you need. Blank fields will not be updated',
  account_form_first_name_label: 'Fist name',
  account_form_first_name_placeholder: 'Your name',
  account_form_save: 'Save',
  account_form_gravatar_one: 'If you want to display your picture, we support Gravatar. Please head to ',
  account_form_gravatar_two: ' to register or update your profile picture. Once updated, please wait a few seconds to see it here.',
  account_my_account_hello: 'Hello! This is where you can manage your preferences',
  account_my_account_logged: 'You\'re logged in as: ',
  account_app_lang_title: 'Change the app language',
  account_app_lang_description: 'You can choose one the languages below',
  account_app_lang_available: 'Available languages',
  account_privacy_little: 'Your Privacy Matters',
  account_privacy_subtitle: 'You decide when to delete your data',
  account_privacy_text: `We're committed to protecting your privacy and
    giving you full control over your data. You can request complete account
    deletion at any time. Once processed, all your personal information will be
    permanently removed from our servers.`,
  account_privacy_delete_btn: 'Delete all my data',
  account_delete_title: 'You are about to delete your account!',
  account_delete_description: `This action cannot be undone. If you really want to
    delete all your data, click the button below. If not, close this message and your
    data will be safe.`,
  account_delete_btn: 'Yes, delete everything',

  footer_my_account: 'My Account ',
  sidebar_last_seen: 'Last seen {{time}}',

  logout: 'Logout'
};

export default enTranslations;
