export const timeAgoTranslations: Record<string, string> = {
  'years ago_pt_br': '{X} anos atrás',
  'year ago_pt_br': '{X} ano atrás',
  'months ago_pt_br': '{X} meses atrás',
  'month ago_pt_br': '{X} mês atrás',
  'days ago_pt_br': '{X} dias atrás',
  'day ago_pt_br': '{X} dia atrás',
  'hours ago_pt_br': '{X} horas atrás',
  'hour ago_pt_br': '{X} hora atrás',
  'minutes ago_pt_br': '{X} minutos atrás',
  'minute ago_pt_br': '{X} minuto atrás',
  'seconds ago_pt_br': '{X} segundos atrás',
  'second ago_pt_br': '{X} segundo atrás',
  'default_pt_br': 'Momentos atrás',

  'years left_pt_br': '{X} anos restantes',
  'year left_pt_br': '{X} ano restante',
  'months left_pt_br': '{X} meses restantes',
  'month left_pt_br': '{X} mês restante',
  'days left_pt_br': '{X} dias restantes',
  'day left_pt_br': '{X} dia restante',
  'due tomorrow_pt_br': 'Vence amanhã',
  'due today_pt_br': 'Vence hoje',

  'years ago_es': 'Hace {X} años',
  'year ago_es': 'Hace {X} año',
  'months ago_es': 'Hace {X} meses',
  'month ago_es': 'Hace {X} mes',
  'days ago_es': 'Hace {X} días',
  'day ago_es': 'Hace {X} día',
  'hours ago_es': 'Hace {X} horas',
  'hour ago_es': 'Hace {X} hora',
  'minutes ago_es': 'Hace {X} minutos',
  'minute ago_es': 'Hace {X} minuto',
  'seconds ago_es': 'Hace {X} segundos',
  'second ago_es': 'Hace {X} segundo',
  'default_es': 'Hace momentos',

  'years left_es': 'Faltan {X} años',
  'year left_es': 'Falta {X} año',
  'months left_es': 'Faltan {X} meses',
  'month left_es': 'Falta {X} mes',
  'days left_es': 'Faltan {X} días',
  'day left_es': 'Falta {X} día',
  'due tomorrow_es': 'Vence mañana',
  'due today_es': 'Vence hoy',

  'years ago_ru': '{X} года назад',
  'year ago_ru': '{X} год назад',
  'months ago_ru': '{X} месяца назад',
  'month ago_ru': '{X} месяц назад',
  'days ago_ru': '{X} дня назад',
  'day ago_ru': '{X} день назад',
  'hours ago_ru': '{X} часа назад',
  'hour ago_ru': '{X} час назад',
  'minutes ago_ru': '{X} минуты назад',
  'minute ago_ru': '{X} минуту назад',
  'seconds ago_ru': '{X} секунды назад',
  'second ago_ru': '{X} секунду назад',
  'default_ru': 'Несколько минут назад',

  'years left_ru': 'осталось {X} года',
  'year left_ru': 'Остался {X} год',
  'months left_ru': 'осталось {X} месяца',
  'month left_ru': 'Остался {X} месяц',
  'days left_ru': 'осталось {X} дня',
  'day left_ru': 'Остался {X} день',
  'due tomorrow_ru': 'Срок завтра',
  'due today_ru': 'Срок сегодня'
};

export const serverResponsesTranslations: Record<string, string> = {
  BAD_PASSWORD_8_pt_br: 'Senha fraca: Senha deve possuir pelo menos 8 letras',
  BAD_PASSWORD_7_pt_br: 'Senha fraca: Senha deve possuir pelo menos 8 letras, 1 caracter especial',
  BAD_PASSWORD_6_pt_br: 'Senha fraca: Senha deve possuir pelo menos 8 letras, 1 número, 1 caracter especial',
  BAD_PASSWORD_5_pt_br: 'Senha fraca: Senha deve possuir pelo menos 8 letras, 1 maiúscula, 1 número, 1 caracter especial',
  BAD_PASSWORD_4_pt_br: 'Senha fraca: Senha deve possuir pelo menos 1 número',
  BAD_PASSWORD_3_pt_br: 'Senha fraca: Senha deve possuir pelo menos 8 letras, 1 maiúscula, 1 caracter especial',
  BAD_PASSWORD_2_pt_br: 'Senha fraca: Senha deve possuir pelo menos 1 maiúscula, 1 caracter especial',
  BAD_PASSWORD_1_pt_br: 'Senha fraca: Senha deve possuir pelo menos 1 caracter especial',
  CONFIRM_EMAIL_TO_GO_ON_pt_br: 'Por favor, confirme seu e-mail antes de continuar',
  EMAIL_EXISTS_pt_br: 'E-mail já cadastrado!',
  FORBIDDEN_pt_br: 'Proibido! Acesso negado',
  INTERNAL_ERROR_pt_br: 'Erro Interno do Servidor!',
  INVALID_CREDENTIALS_pt_br: 'E-mail ou senha inválidos!',
  MAX_LOGIN_ATTEMPT_pt_br: 'Limite máximo de tentativas atingido. Por favor aguarde 30 minutos',
  NETWORK_ERROR_pt_br: 'Erro de rede ao tentar obter recursos.',
  FILL_ALL_FIELDS_pt_br: 'Por favor, preencha todos os campos',
  FILL_NEW_PASSWORD_pt_br: 'Por favor, informe a nova senha',
  FILL_USER_pt_br: 'Por favor, informe seu e-mail',
  FILL_USER_AND_PASS_pt_br: 'Por favor, informe seu e-mail e senha!',
  FILL_AT_LEAST_3_pt_br: 'Por favor, digite pelo menos 3 letras',
  MAX_TEXT_LENGTH_2000_pt_br: 'O tamanho máximo do texto é 2000',
  RECOVER_PASSWORD_pt_br: 'Se o endereço de e-mail informado estiver associado a uma conta, você receberá um link para resetar a senha em breve.',
  UNKNOWN_pt_br: 'Erro desconhecido',
  WRONG_IDENTIFICATION_pt_br: 'Identificação incorreta ou faltando',
  WRONG_OR_MISSING_INFO_pt_br: 'Informação errada ou incompleta!',
  NOTHING_TO_UPDATE_pt_br: 'Nada para atualizar!',
  EMAIL_NOT_CONFIRMED_pt_br: 'E-mail não confirmado!',
  CONFIRMATION_RESENT_pt_br: 'E-mail de confirmação reenviado! Por favor, verifique a pasta de spam.',

  BAD_PASSWORD_8_es: 'Contraseña inválida: La contraseña debe tener al menos 8 caracteres',
  BAD_PASSWORD_7_es: 'Contraseña inválida: La contraseña debe tener al menos 8 caracteres, 1 carácter especial',
  BAD_PASSWORD_6_es: 'Contraseña inválida: La contraseña debe tener al menos 8 caracteres, 1 número, 1 carácter especial',
  BAD_PASSWORD_5_es: 'Contraseña inválida: La contraseña debe tener al menos 8 caracteres, 1 mayúscula, 1 número, 1 carácter especial',
  BAD_PASSWORD_4_es: 'Contraseña inválida: La contraseña debe tener al menos 1 número',
  BAD_PASSWORD_3_es: 'Contraseña inválida: La contraseña debe tener al menos 8 caracteres, 1 mayúscula y 1 carácter especial',
  BAD_PASSWORD_2_es: 'Contraseña inválida: La contraseña debe tener al menos 1 mayúscula y 1 carácter especial',
  BAD_PASSWORD_1_es: 'Contraseña inválida: La contraseña debe tener al menos 1 carácter especial',
  CONFIRM_EMAIL_TO_GO_ON_es: 'Por favor, confirme su correo electrónico antes de continuar',
  EMAIL_EXISTS_es: '¡El correo ya está registrado!',
  FORBIDDEN_es: '¡Prohibido! Acceso denegado',
  INTERNAL_ERROR_es: '¡Error interno del servidor!',
  INVALID_CREDENTIALS_es: '¡Usuario o contraseña incorrectos!',
  MAX_LOGIN_ATTEMPT_es: 'Has alcanzado el límite máximo de intentos de inicio de sesión. Por favor, espera 30 minutos',
  NETWORK_ERROR_es: 'Error de red al intentar obtener el recurso.',
  FILL_ALL_FIELDS_es: 'Por favor, completa todos los campos',
  FILL_NEW_PASSWORD_es: 'Por favor, rellene la nueva contraseña',
  FILL_USER_es: 'Por favor, ingresa tu correo electronico',
  FILL_USER_AND_PASS_es: '¡Por favor, ingresa tu correo electronico y contraseña!',
  FILL_AT_LEAST_3_es: '¡Por favor, escriba al menos 3 caracteres!',
  MAX_TEXT_LENGTH_2000_es: 'La longitud máxima del texto es 2000',
  RECOVER_PASSWORD_es: 'Si la dirección de correo electrónico ingresada está asociada a una cuenta, recibirá un enlace para restablecer su contraseña en breve.',
  UNKNOWN_es: 'Error desconocido',
  WRONG_IDENTIFICATION_es: 'Identificación incorrecta o faltante',
  WRONG_OR_MISSING_INFO_es: '¡Información incorrecta o incompleta!',
  NOTHING_TO_UPDATE_es: '¡Nada que actualizar!',
  EMAIL_NOT_CONFIRMED_es: '¡Correo no confirmado!',
  CONFIRMATION_RESENT_es: '¡Correo de confirmación reenviado! Por favor, revisa la carpeta de spam.',

  BAD_PASSWORD_8_ru: 'Неправильный пароль: Пароль должен содержать не менее 8 символов.',
  BAD_PASSWORD_7_ru: 'Неправильный пароль: Пароль должен содержать не менее 8 символов, 1 специальный символ.',
  BAD_PASSWORD_6_ru: 'Неправильный пароль: Пароль должен содержать не менее 8 символов, 1 цифру, 1 специальный символ.',
  BAD_PASSWORD_5_ru: 'Неправильный пароль: Пароль должен содержать не менее 8 символов, 1 заглавную букву, 1 цифру, 1 специальный символ.',
  BAD_PASSWORD_4_ru: 'Неправильный пароль: Пароль должен содержать не менее 1 цифры.',
  BAD_PASSWORD_3_ru: 'Неправильный пароль: Пароль должен содержать не менее 8 символов, 1 заглавную букву, 1 специальный символ.',
  BAD_PASSWORD_2_ru: 'Неправильный пароль: Пароль должен содержать как минимум 1 заглавную букву и 1 специальный символ.',
  BAD_PASSWORD_1_ru: 'Неправильный пароль: Пароль должен содержать хотя бы 1 специальный символ.',
  CONFIRM_EMAIL_TO_GO_ON_ru: 'Пожалуйста, подтвердите свой адрес электронной почты, прежде чем продолжить',
  EMAIL_EXISTS_ru: 'Электронная почта уже используется!',
  FORBIDDEN_ru: 'Доступ запрещен!',
  INTERNAL_ERROR_ru: 'Внутренняя ошибка сервера!',
  INVALID_CREDENTIALS_ru: 'Неправильный пользователь или пароль',
  MAX_LOGIN_ATTEMPT_ru: 'Достигнут максимальный лимит попыток входа. Пожалуйста, подождите 30 минут',
  NETWORK_ERROR_ru: 'Ошибка сети при попытке получить ресурс.',
  FILL_ALL_FIELDS_ru: 'Пожалуйста, заполните все поля',
  FILL_NEW_PASSWORD_ru: 'Пожалуйста, введите новый пароль',
  FILL_USER_ru: 'Пожалуйста, введите свой адрес электронной почты',
  FILL_USER_AND_PASS_ru: 'Пожалуйста, введите свое имя пользователя и пароль!',
  FILL_AT_LEAST_3_ru: 'Пожалуйста, введите не менее 3 символов',
  MAX_TEXT_LENGTH_2000_ru: 'Максимальная длина текста — 2000 символов.',
  RECOVER_PASSWORD_ru: 'Если введенный вами адрес электронной почты связан с учетной записью, вы вскоре получите ссылку для сброса пароля.',
  UNKNOWN_ru: 'Неизвестная ошибка',
  WRONG_IDENTIFICATION_ru: 'Неправильная или отсутствующая идентификация',
  WRONG_OR_MISSING_INFO_ru: 'Неверная или отсутствующая информация!',
  NOTHING_TO_UPDATE_ru: 'Нечего обновлять!',
  EMAIL_NOT_CONFIRMED_ru: 'Электронная почта не подтверждена!',
  CONFIRMATION_RESENT_ru: 'Письмо с подтверждением отправлено еще раз! Пожалуйста, проверьте папку со спамом.'
};
