const ptBrTranslations = {
  landing_title: 'Bem vindo ao TaskNote',
  landing_subtitle: 'Seu melhor aliado para organizar tarefas e notas!',
  landing_btn_login: 'Entrar',
  landing_btn_register: 'Criar conta',
  landing_btn_english: 'English',
  landing_btn_portuguese: 'Português (BR)',
  landing_btn_spanish: 'Español',
  landing_btn_russian: 'Русский',
  landing_languages: 'Você pode escolher um destes idiomas',

  password_show_txt: 'Mostrar',
  password_hide_txt: 'Esconder',
  password_helper: 'A senha deve ter no mínimo 8 caracteres e incluir um número, uma letra maiúscula, e um caracter especial',

  login_title: 'Entrar',
  login_email_label: 'E-mail',
  login_email_placeholder: 'Digite seu e-mail',
  login_password_label: 'Senha',
  login_password_placeholder: 'Digite sua senha',
  login_btn_submit: 'Entrar',
  login_account: 'Não possui uma conta ainda?',
  login_go_other: 'Criar conta',
  login_back_home: 'Voltar para o início',
  login_forgot_password: 'Esqueceu sua senha?',

  register_title: 'Criar conta',
  register_email_label: 'E-mail',
  register_email_placeholder: 'Digite seu e-mail',
  register_password_label: 'Senha',
  register_password_placeholder: 'Digite sua senha',
  register_password_repeat_label: 'Repetir senha',
  register_btn_submit: 'Criar conta',
  register_account: 'Já possui conta?',
  register_go_other: 'Entrar',
  register_back_home: 'Voltar para o início',
  register_resent_email: 'Re-enviar e-mail de confirmação',
  register_resent_email_secs: 'Re-enviar em ',

  reset_title: 'Resete sua senha',
  reset_email_label: 'E-mail',
  reset_email_placeholder: 'Digite seu e-mail',
  reset_password_label: 'Senha',
  reset_password_placeholder: 'Digite sua senha',
  reset_btn_submit: 'Enviar e-mail de confirmação',
  reset_account: 'Lembrou da sua senha?',
  reset_go_other: 'Entrar',
  reset_back_home: 'Voltar para o início',

  complete_reset_title: 'Crie sua nova senha',
  complete_reset_password_label: 'Senha',
  complete_reset_password_placeholder: 'Digite sua senha',
  complete_reset_btn_submit: 'Resetar',
  complete_reset_account: 'Lembrou da sua senha?',
  complete_reset_go_other: 'Login',
  complete_reset_back_home: 'Voltar para o início',

  email_confirmation_loading: 'Confirmando seu endereço de e-mail...',
  email_confirmation_success: '✅ E-mail confirmado',
  email_confirmation_success_text: 'Obrigado! Seu endereço de e-mail foi confirmado com sucesso. Agora você pode voltar ao app TaskNote e entrar.',
  email_confirmation_btn: 'Entrar',

  home_nav_home: 'Início',
  home_nav_tasks: 'Tarefas',
  home_nav_notes: 'Notas',
  home_nav_about: 'Sobre',
  home_welcome_title: 'Olá, ',
  home_welcome_subtitle: 'Bem vindo ao TaskNote! Se prepare para completar suas tarefas pendentes',
  home_welcome_start: 'Comece Seu Dia, Seja',
  home_welcome_productive: 'Produtivo(a)',
  home_input_filter: 'Filtrar tarefas e notas',
  home_radio_everything: 'Tudo',
  home_radio_tasks: 'Tarefas',
  home_radio_notes: 'Notas',
  home_card_task_title: 'Resumo de Tarefas',
  home_card_task_pending: 'Tarefa(s) pendente(s)',
  home_card_task_empty: 'Nenhuma tarefa pendente',
  home_card_task_done: 'tarefa(s) concluída(s)',
  home_completed_tasks_title: 'Tarefas concluídas',
  home_archived_notes_title: 'Notas arquivadas',
  home_card_task_done_empty: 'Nenhuma tarefa condluída',
  home_card_task_btn: 'Ir para Tarefas',
  home_card_note_title: 'Resumo de Notas',
  home_card_note_count: 'Nota(s)',
  home_card_note_btn: 'Ir para Notas',
  home_card_search_label: 'Buscar tarefas e notas',
  home_card_search_placeholder: 'Digite o termo de basca...',
  home_card_search_btn: 'Buscar',
  home_card_search_result_label: 'Resultados da busca',
  home_card_search_empty_result: 'Nenhum resultado',

  task_form_title: 'Adicionar tarefa',
  task_form_desc_label: 'Descrição',
  task_form_desc_placeholder: 'Digite a descrição da tarefa',
  task_form_url_label: 'URL',
  task_form_url_placeholder: 'URL (Opcional)',
  task_form_duedate_label: 'Data de vencimento',
  task_form_duedate_placeholder: 'Data de vencimento (Opcional)',
  task_form_submit: 'Salvar tarefa',
  task_table_description: 'Descrição',
  task_table_done: 'Concluída',
  task_table_actions: 'Ações',
  task_table_action_done: 'Finalizada',
  task_table_action_undone: 'Desfazer',
  task_table_action_done_yes: 'Sim',
  task_table_action_done_no: 'Não',
  task_table_action_edit: 'Alterar',
  task_table_action_clone: 'Clonar',
  task_table_action_delete: 'Excluir',
  delete_modal_title: 'Confirmar exclusão',
  delete_modal_body: 'Tem certeza de que deseja excluir este item? Esta ação não pode ser desfeita.',
  delete_modal_cancel: 'Cancelar',
  delete_modal_confirm: 'Excluir',

  note_form_title: 'Adicionar nota',
  note_form_title_label: 'Título',
  note_form_title_placeholder: 'Digite o título da nota',
  note_form_content_label: 'Conteúdo da nota',
  note_form_content_placeholder: 'Digite o conteúdo da nota',
  note_form_submit: 'Salvar nota',
  note_table_btn_edit: 'Alterar',
  note_table_btn_delete: 'Excluir',
  note_action_share: 'Compartilhar',
  note_action_unshare: 'Parar de compartilhar',
  note_action_copy_link: 'Copiar link',
  note_action_archive: 'Arquivar',
  note_action_restore: 'Restaurar',
  note_action_delete_permanently: 'Excluir permanentemente',

  about_page_title_one: 'Sobre o',
  about_page_title_two: 'App TaskNote',
  about_page_title_three: 'Tarefas e notas de forma',
  about_page_title_four: 'Fácil',
  about_page_subtitle: 'Saiba mais sobre nós e sobre o app',
  about_app_title: 'Sobre o TaskNote',
  about_app_description: `TaskNote é sua aplicação ideal para gerenciamento
    de tarefas e notas em apenas um lugar. Esteja você buscando registrar sua
    lista de tarefas ou organizar suas notas de reuniões importantes, TaskNote
    te ajuda a se manter organizado(a) e produtivo(a).`,

  about_app_features: 'Funções',
  about_app_features_one: 'Adicionar e gerenciar tarefas e notas rapidamente',
  about_app_features_two: 'Buscar e filtrar notas para fácil acesso',
  about_app_features_three: 'Interface limpa e intuitiva',
  about_app_features_four: 'Suporte a tema escuro e claro com design responsivo',
  about_app_features_five: 'Anexos de URL para tarefas e notas',
  about_app_features_six: 'Sistema de tags com múltiplas tags por item',
  about_app_features_seven: 'Compartilhamento público de notas via links públicos',
  about_app_features_eight: 'Barra de ferramentas de formatação Markdown para edição de texto rico',
  about_app_features_nine: 'Confirmação de e-mail obrigatória para segurança da conta',
  about_app_help_title: 'Ajuda & Como usar',
  about_app_help_description: `Para começar, simplemente crie sua conta ou entre,
    e você terá acesso ao seu painel personalizado. A partir daí, você pode criar,
    alterar, e apagar tarefas e notas, e organizá-las da forma que preferir. Precisa
    de alguma ajuda? Confira a barra lateral para navegação rápida.`,

  about_tech_title: 'Tecnologia',
  about_tech_description: `TaskNote foi contruído com tecnologia web atual
    que garante velocidade, confiabilidade e segurança.`,
  about_tech_list_one: 'React 19 com TypeScript para o desenvolvimento do front-end',
  about_tech_list_two: 'Vite para builds e desenvolvimento rápidos',
  about_tech_list_three: 'React Router 7 para roteamento no lado do cliente',
  about_tech_list_four: 'i18next para suporte à internacionalização',
  about_tech_list_five: 'Bootstrap 5 para os componentes e design responsivo',
  about_tech_list_six: 'Java e Spring Boot 4.x mais GraalVM para o back-end Nativo em Cloud',
  about_tech_list_seven: 'PostgreSQL para gestão do banco de dados',
  about_tech_list_eight: 'Docker para isolamento em containers e lançamentos',
  about_tech_list_nine: 'GitHub Actions para integração contínua, testes e controle de qualidade',
  about_tech_list_ten: 'SonarCloud e GitHub QL para reforço de qualidade e melhorias',

  about_dev_title: 'Sobre o Desenvolvedor',
  about_dev_description: `Olá! Sou o Ricardo, o desenvolvedor do TaskNote. 
    Sou apaixonado por criar aplicações que fazem a vida mais fácil e organizada.
    Você pode me contactar em `,
  about_dev_description_two: ' para qualquer dúvida ou comentário.',
  about_buy_coffee_one: 'Você também pode ',
  about_buy_coffee_link: 'Me pagar um café',

  account_header_my: 'Minha',
  account_header_account: 'Conta',
  account_header_update_manage: 'Atualize e Gerencie, Seus',
  account_header_data: 'Dados',
  account_data_update_header: 'Atualize apenas o que você precisa. Campos em branco não serão atualizados',
  account_form_first_name_label: 'Primeiro nome',
  account_form_first_name_placeholder: 'Seu nome',
  account_form_save: 'Salvar',
  account_form_gravatar_one: 'Se você quer adicionar sua foto, nós suportamos Gravatar. Por favor acesse ',
  account_form_gravatar_two: ' para se registrar ou atualizar seu perfil. Uma vez atualizado, por favor aguarde alguns segundos para vê-la aqui.',
  account_my_account_hello: 'Olá! Aqui é onde você pode gerenciar suas preferências.',
  account_my_account_logged: 'Você está logado como: ',
  account_app_lang_title: 'Mude o idioma do app',
  account_app_lang_description: 'Você pode escolher um destes idiomas:',
  account_app_lang_available: 'Idiomas disponívels',
  account_privacy_little: 'Sua Privacidade Importa',
  account_privacy_subtitle: 'Você decide quanto excluir seus dados',
  account_privacy_text: `Estamos comprometidos em proteger sua privacidade e te dar
    controle total sobre seus dados. Você pode solicitar a remoção completa da sua conta
    a qualquer hora. Uma vez processado, todos os seus dados pessoais serão excluídos
    permanentemente dos nossos servidores.`,
  account_privacy_delete_btn: 'Excluir minha conta',
  account_delete_title: 'Você está prestes a deletar sua conta!',
  account_delete_description: `Esta ação não pode ser desfeita. Se você realmente
   quer deletar todos os seus dados, clique no botão abaixo. Caso contrário, feche
   esta mensagem e seus dados estarão seguros.`,
  account_delete_btn: 'Sim, deletar tudo',

  footer_my_account: 'Minha Conta ',
  sidebar_last_seen: 'Último acesso {{time}}',

  logout: 'Sair'
};

export default ptBrTranslations;
