const ruTranslations = {
  landing_title: 'Добро пожаловать в TaskNote',
  landing_subtitle: 'Ваш лучший помощник для заметок и задач!',
  landing_btn_login: 'Войти',
  landing_btn_register: 'Зарегистрироваться',
  landing_btn_english: 'English',
  landing_btn_portuguese: 'Português (BR)',
  landing_btn_spanish: 'Español',
  landing_btn_russian: 'Русский',
  landing_languages: 'Вы можете выбрать один из этих языков',

  password_show_txt: 'Показать',
  password_hide_txt: 'Скрыть',
  password_helper: 'Пароль должен быть длиной не менее 8 символов и включать цифру, заглавную букву и специальный символ',

  login_title: 'Войти',
  login_email_label: 'Электронная почта',
  login_email_placeholder: 'Введите вашу электронную почту',
  login_password_label: 'Пароль',
  login_password_placeholder: 'Введите ваш пароль',
  login_btn_submit: 'Войти',
  login_account: 'Ещё нет аккаунта?',
  login_go_other: 'Создать аккаунт',
  login_back_home: 'Вернуться на главную',
  login_forgot_password: 'Забыли пароль?',

  register_title: 'Создать аккаунт',
  register_email_label: 'Электронная почта',
  register_email_placeholder: 'Введите вашу электронную почту',
  register_password_label: 'Пароль',
  register_password_placeholder: 'Введите ваш пароль',
  register_password_repeat_label: 'Повторите пароль',
  register_btn_submit: 'Создать аккаунт',
  register_account: 'Уже есть аккаунт?',
  register_go_other: 'Войти',
  register_back_home: 'Вернуться на главную',
  register_resent_email: 'Повторно отправить письмо с подтверждением',
  register_resent_email_secs: 'Повторно отправить в ',

  reset_title: 'Сбросьте свой пароль',
  reset_email_label: 'Электронная почта',
  reset_email_placeholder: 'Введите вашу электронную почту',
  reset_password_label: 'Пароль',
  reset_password_placeholder: 'Введите ваш пароль',
  reset_btn_submit: 'Отправить подтверждение по электронной почте',
  reset_account: 'Вы вспомнили свой пароль?',
  reset_go_other: 'Войти',
  reset_back_home: 'Вернуться на главную',

  complete_reset_title: 'Создайте новый пароль',
  complete_reset_password_label: 'Пароль',
  complete_reset_password_placeholder: 'Введите ваш пароль',
  complete_reset_btn_submit: 'Reset',
  complete_reset_account: 'Вы вспомнили свой пароль?',
  complete_reset_go_other: 'Войти',
  complete_reset_back_home: 'Вернуться на главную',

  email_confirmation_loading: 'Подтверждение вашего адреса электронной почты...',
  email_confirmation_success: '✅ Электронная почта подтверждена',
  email_confirmation_success_text: 'Спасибо! Ваш адрес электронной почты успешно подтвержден. Теперь вы можете вернуться в приложение TaskNote и войти в систему.',
  email_confirmation_btn: 'Войти',

  home_nav_home: 'Главная',
  home_nav_tasks: 'Задачи',
  home_nav_notes: 'Заметки',
  home_nav_about: 'О приложении',
  home_welcome_title: 'Привет, ',
  home_welcome_subtitle: 'Добро пожаловать в TaskNote! Приготовьтесь завершить свои отложенные задачи',
  home_welcome_start: 'Начните свой день, будьте',
  home_welcome_productive: 'Продуктивный',
  home_input_filter: 'Фильтровать задачи и заметки',
  home_radio_everything: 'Все',
  home_radio_tasks: 'Задачи',
  home_radio_notes: 'Заметки',
  home_card_task_title: 'Обзор задач',
  home_card_task_pending: 'Незавершённые задачи',
  home_card_task_empty: 'Нет незавершённых задач',
  home_card_task_done: 'выполненные задачи!',
  home_completed_tasks_title: 'Выполненные задачи',
  home_archived_notes_title: 'Архивированные заметки',
  home_card_task_done_empty: 'Нет выполненных задач!',
  home_card_task_btn: 'Перейти к задачам',
  home_card_note_title: 'Обзор заметок',
  home_card_note_count: 'Примечания',
  home_card_note_btn: 'Перейти к заметкам',
  home_card_search_label: 'Искать задачи и заметки',
  home_card_search_placeholder: 'Введите запрос',
  home_card_search_btn: 'Искать',
  home_card_search_result_label: 'Результаты поиска',
  home_card_search_empty_result: 'Нет результатов',

  task_form_title: 'Добавить задачу',
  task_form_desc_label: 'Описание',
  task_form_desc_placeholder: 'Введите описание задачи',
  task_form_url_label: 'URL',
  task_form_url_placeholder: 'URL-адрес (необязательно)',
  task_form_duedate_label: 'Срок оплаты',
  task_form_duedate_placeholder: 'Срок выполнения (необязательно)',
  task_form_submit: 'Сохранить задачу',
  task_table_description: 'Описание',
  task_table_done: 'Завершённый',
  task_table_actions: 'Действия',
  task_table_action_done: 'Завершённый',
  task_table_action_undone: 'Отменено',
  task_table_action_done_yes: 'Да',
  task_table_action_done_no: 'Нет',
  task_table_action_edit: 'Редактировать',
  task_table_action_clone: 'Клонировать',
  task_table_action_delete: 'Удалить',
  delete_modal_title: 'Подтвердите удаление',
  delete_modal_body: 'Вы уверены, что хотите удалить этот элемент? Это действие не может быть отменено.',
  delete_modal_cancel: 'Отмена',
  delete_modal_confirm: 'Удалить',

  note_form_title: 'Добавить примечание',
  note_form_title_label: 'Заголовок',
  note_form_title_placeholder: 'Введите название заметки',
  note_form_content_label: 'Примечание к содержанию',
  note_form_content_placeholder: 'Введите содержание заметки',
  note_form_submit: 'Сохранить заметку',
  note_table_btn_edit: 'Редактировать',
  note_table_btn_delete: 'Удалить',
  note_action_share: 'Поделиться',
  note_action_unshare: 'Закрыть доступ',
  note_action_copy_link: 'Копировать ссылку',
  note_action_archive: 'Архивировать',
  note_action_restore: 'Восстановить',
  note_action_delete_permanently: 'Удалить навсегда',

  about_page_title_one: 'около',
  about_page_title_two: 'TaskNote App',
  about_page_title_three: 'Задачи и заметки стали',
  about_page_title_four: 'проще',
  about_page_subtitle: '  Узнайте больше о нас и приложении',
  about_app_title: 'О TaskNote',
  about_app_description: `TaskNote — это ваше приложение для управления
    задачами и заметками в одном удобном месте. Независимо от того, отслеживаете ли вы
    ежедневные задачи или организуете заметки с важных встреч, TaskNote помогает
    вам оставаться организованными и продуктивными.`,
  about_app_features: 'Функции',
  about_app_features_one: 'Быстро добавляйте и управляйте задачами и заметками',
  about_app_features_two: 'Поиск и фильтрация заметок для легкого доступа',
  about_app_features_three: 'Интуитивно понятный пользовательский интерфейс',
  about_app_features_four: 'Поддержка тёмной и светлой темы с адаптивным дизайном',
  about_app_features_five: 'URL-вложения для задач и заметок',
  about_app_features_six: 'Система тегов с несколькими тегами на элемент',
  about_app_features_seven: 'Публичный доступ к заметкам через публичные ссылки',
  about_app_features_eight: 'Панель инструментов форматирования Markdown для редактирования',
  about_app_features_nine: 'Требуется подтверждение электронной почты для безопасности аккаунта',
  about_app_help_title: 'Помощь и как использовать',
  about_app_help_description: `Чтобы начать, просто зарегистрируйтесь или войдите в систему, и
    вы получите доступ к своей персонализированной панели. Оттуда вы можете
    создавать, редактировать и удалять задачи и заметки, а также организовывать их так, как вам
    нравится. Нужна помощь? Ознакомьтесь с боковой панелью для быстрой навигации.`,

  about_tech_title: 'Технологии',
  about_tech_description: `TaskNote был создан с использованием современных веб-технологий, 
      которые обеспечивают скорость, надежность и безопасность.`,
  about_tech_list_one: 'React 19 с TypeScript для фронтенда',
  about_tech_list_two: 'Vite для быстрой сборки и разработки',
  about_tech_list_three: 'React Router 7 для маршрутизации на стороне клиента',
  about_tech_list_four: 'i18next для поддержки интернационализации',
  about_tech_list_five: 'Bootstrap 5 для компонентов и адаптивного дизайна',
  about_tech_list_six: 'Java и Spring Boot 4.x плюс GraalVM для бэкенда и Cloud Native',
  about_tech_list_seven: 'PostgreSQL для управления базами данных',
  about_tech_list_eight: 'Docker для контейнеризации и развертывания',
  about_tech_list_nine: 'GitHub Actions для CI/CD, тестирования и принудительного линтинга',
  about_tech_list_ten: 'SonarCloud и GitHub QL для проверок безопасности и улучшений',

  about_dev_title: 'О разработчике',
  about_dev_description: `Привет! Я Рикардо, разработчик TaskNote. Я увлечен созданием приложений,
    которые делают жизнь проще и более
    организованной. Вы можете связаться со мной по адресу `,
  about_dev_description_two: ' для любых вопросов или отзывов.',
  about_buy_coffee_one: 'Ты также можешь ',
  about_buy_coffee_link: 'купить мне кофе.',

  account_header_my: 'Мой',
  account_header_account: 'аккаунт',
  account_header_update_manage: 'Обновление и управление',
  account_header_data: 'данные',
  account_data_update_header: 'Обновляйте только то, что вам нужно. Пустые поля не будут обновлены',
  account_form_first_name_label: 'имя',
  account_form_first_name_placeholder: 'Ваше имя',
  account_form_save: 'Сохранить',
  account_form_gravatar_one: 'Если вы хотите показать свою фотографию, мы поддерживаем Gravatar. Пожалуйста, перейдите на ',
  account_form_gravatar_two: ' для регистрации или обновления вашего фото профиля. После обновления, пожалуйста, подождите несколько секунд, чтобы увидеть его здесь.',
  account_my_account_hello: 'Привет! Здесь вы можете управлять своими предпочтениями.',
  account_my_account_logged: 'Вы вошли как:',
  account_app_lang_title: 'Изменить язык приложения',
  account_app_lang_description: 'Вы можете выбрать один из этих языков:',
  account_app_lang_available: 'Доступные языки',
  account_privacy_little: 'Ваша конфиденциальность имеет значение',
  account_privacy_subtitle: 'Вы сами решаете, когда удалять свои данные',
  account_privacy_text: `Мы стремимся защищать вашу конфиденциальность и
    предоставлять вам полный контроль над вашими данными. Вы можете запросить полное удаление
    аккаунта в любое время. После обработки вся ваша личная информация будет
    навсегда удалена с наших серверов.`,
  account_privacy_delete_btn: 'Удалить все мои данные',
  account_delete_title: 'Вы собираетесь удалить свой аккаунт!',
  account_delete_description: `Это действие нельзя отменить. Если вы действительно хотите
    удалить все свои данные, введите текущий пароль и нажмите кнопку ниже. Если нет,
    закройте это сообщение, и ваши данные будут в безопасности.`,
  account_delete_btn: 'Да, удалить все',

  footer_my_account: 'Мой аккаунт ',
  sidebar_last_seen: 'Последний вход {{time}}',

  logout: 'Выйти'
};

export default ruTranslations;
