export const serverResponses: Record<string, string> = {
  'Bad password: Password must have at least at least 8 characters': 'BAD_PASSWORD_8',
  'Bad password: Password must have at least at least 8 characters, 1 special character': 'BAD_PASSWORD_7',
  'Bad password: Password must have at least at least 8 characters, 1 number, 1 special character': 'BAD_PASSWORD_6',
  'Bad password: Password must have at least at least 8 characters, 1 uppercase, 1 number, 1 special character': 'BAD_PASSWORD_5',
  'Bad password: Password must have at least at least 8 characters, 1 uppercase, 1 special character': 'BAD_PASSWORD_3',
  'Bad password: Password must have at least 1 uppercase, 1 special character': 'BAD_PASSWORD_2',
  'Bad password: Password must have at least 1 special character': 'BAD_PASSWORD_1',
  'Bad password: Password must have at least 1 number': 'BAD_PASSWORD_4',
  'Email already exists!': 'EMAIL_EXISTS',
  'Forbidden! Access denied!': 'FORBIDDEN',
  'If the email address you entered is associated with an account, you will receive a password reset link shortly.': 'RECOVER_PASSWORD',
  'Internal Server Error!': 'INTERNAL_ERROR',
  'Max login attempt limit reached. Please wait 3 minutes': 'MAX_LOGIN_ATTEMPT',
  'NetworkError when attempting to fetch resource.': 'NETWORK_ERROR',
  'Please confirm your email before proceeding': 'CONFIRM_EMAIL_TO_GO_ON',
  'Please fill in all the fields': 'FILL_ALL_FIELDS',
  'Please fill in your email': 'FILL_USER',
  'Please fill in your username and password!': 'FILL_USER_AND_PASS',
  'Please fill in the new password': 'FILL_NEW_PASSWORD',
  'Please type at least 3 characters': 'FILL_AT_LEAST_3',
  'The maximum text length is 2000': 'MAX_TEXT_LENGTH_2000',
  'Unknown error': 'UNKNOWN',
  'Wrong or missing identification': 'WRONG_IDENTIFICATION',
  'Wrong or missing information!': 'WRONG_OR_MISSING_INFO',
  'Invalid credentials': 'INVALID_CREDENTIALS',
  'Nothing to update!': 'NOTHING_TO_UPDATE',
  'Email not confirmed!': 'EMAIL_NOT_CONFIRMED',
  'Confirmation email re-sent! Please check the spam folder.': 'CONFIRMATION_RESENT'
};
