const esTranslations = {
  landing_title: 'Bienvenido a TaskNote',
  landing_subtitle: '¡Tu mejor aliado para organizar tareas y notas!',
  landing_btn_login: 'Iniciar sesión',
  landing_btn_register: 'Crear cuenta',
  landing_btn_english: 'English',
  landing_btn_portuguese: 'Português (BR)',
  landing_btn_spanish: 'Español',
  landing_btn_russian: 'Русский',
  landing_languages: 'Puedes elegir uno de estos idiomas',

  password_show_txt: 'Mostrar',
  password_hide_txt: 'Ocultar',
  password_helper: 'La contraseña debe tener al menos 8 caracteres e incluir un número, una letra mayúscula y un carácter especial',

  login_title: 'Acceso',
  login_email_label: 'Correo electrónico',
  login_email_placeholder: 'Escribe tu correo aquí',
  login_password_label: 'Contraseña',
  login_password_placeholder: 'Escribe tu contraseña aquí',
  login_btn_submit: 'Iniciar sesión',
  login_account: '¿No tienes una cuenta?',
  login_go_other: 'Regístrate aquí',
  login_back_home: 'Volver a inicio',
  login_forgot_password: '¿Olvidaste tu contraseña?',

  register_title: 'Crear cuenta',
  register_email_label: 'Correo electrónico',
  register_email_placeholder: 'Escribe tu correo aquí',
  register_password_label: 'Contraseña',
  register_password_placeholder: 'Escribe tu contraseña aquí',
  register_password_repeat_label: 'Repita la contraseña',
  register_btn_submit: 'Crear cuenta',
  register_account: '¿Ya tienes una cuenta?',
  register_go_other: 'Ir a iniciar sesión',
  register_back_home: 'Volver a inicio',
  register_resent_email: 'Reenviar correo electrónico de confirmación',
  register_resent_email_secs: 'Reenviar en ',

  reset_title: 'Restablecer su contraseña',
  reset_email_label: 'Correo electrónico',
  reset_email_placeholder: 'Escribe tu correo aquí',
  reset_password_label: 'Contraseña',
  reset_password_placeholder: 'Escribe tu contraseña aquí',
  reset_btn_submit: 'Enviar correo electrónico de confirmación',
  reset_account: '¿Has recordado tu contraseña?',
  reset_go_other: 'Ir a iniciar sesión',
  reset_back_home: 'Volver a inicio',

  complete_reset_title: 'Crea tu nueva contraseña',
  complete_reset_password_label: 'Contraseña',
  complete_reset_password_placeholder: 'Escribe tu contraseña aquí',
  complete_reset_btn_submit: 'Reiniciar',
  complete_reset_account: '¿Has recordado tu contraseña?',
  complete_reset_go_other: 'Ir a iniciar sesión',
  complete_reset_back_home: 'Volver a inicio',

  email_confirmation_loading: 'Confirmando su dirección de correo electrónico...',
  email_confirmation_success: '✅ Correo electrónico confirmado',
  email_confirmation_success_text: '¡Gracias! Tu dirección de correo electrónico se ha confirmado correctamente. Ya puedes volver a la app TaskNote e iniciar sesión.',
  email_confirmation_btn: 'Iniciar sesión',

  home_nav_home: 'Início',
  home_nav_tasks: 'Tareas',
  home_nav_notes: 'Notas',
  home_nav_about: 'Acerca de',
  home_welcome_title: 'Hola, ',
  home_welcome_subtitle: '¡Bienvenido a TaskNote! Prepárate para completar tus tareas pendientes.',
  home_welcome_start: 'Comienza Tu Día, Sé',
  home_welcome_productive: 'Productivo(a)',
  home_input_filter: 'Filtrar tareas y notas',
  home_radio_everything: 'Todo',
  home_radio_tasks: 'Tareas',
  home_radio_notes: 'Notas',
  home_card_task_title: 'Resumen de Tareas',
  home_card_task_pending: 'Tarea(s) pendiente(s)',
  home_card_task_empty: 'No tienes tareas pendientes',
  home_card_task_done: 'tarea(s) completada(s)',
  home_completed_tasks_title: 'Tareas completadas',
  home_archived_notes_title: 'Notas archivadas',
  home_card_task_done_empty: 'No tareas completadas',
  home_card_task_btn: 'Ir a Tareas',
  home_card_note_title: 'Resumen de Notas',
  home_card_note_count: 'Nota(s)',
  home_card_note_btn: 'Ir a Notas',
  home_card_search_label: 'Buscar tareas y notas',
  home_card_search_placeholder: 'Escribe tu búsqueda...',
  home_card_search_btn: 'Buscar',
  home_card_search_result_label: 'Resultados de la búsqueda',
  home_card_search_empty_result: 'No hay resultados',

  task_form_title: 'Añadir tarea',
  task_form_desc_label: 'Descripción',
  task_form_desc_placeholder: 'Introduce la descripción de la tarea',
  task_form_url_label: 'URL',
  task_form_url_placeholder: 'URL (opcional)',
  task_form_duedate_label: 'Fecha de vencimiento',
  task_form_duedate_placeholder: 'Fecha de vencimiento (Opcional)',
  task_form_submit: 'Guardar tarea',
  task_table_description: 'Descripción',
  task_table_done: 'Completada',
  task_table_actions: 'Acciones',
  task_table_action_done: 'Completada',
  task_table_action_undone: 'Deshacer',
  task_table_action_done_yes: 'Sí',
  task_table_action_done_no: 'No',
  task_table_action_edit: 'Editar',
  task_table_action_clone: 'Clonar',
  task_table_action_delete: 'Eliminar',
  delete_modal_title: 'Confirmar eliminación',
  delete_modal_body: '¿Estás seguro de que deseas eliminar este elemento? Esta acción no se puede deshacer.',
  delete_modal_cancel: 'Cancelar',
  delete_modal_confirm: 'Eliminar',

  note_form_title: 'Añadir nota',
  note_form_title_label: 'Título',
  note_form_title_placeholder: 'Introduce el título de la nota',
  note_form_content_label: 'Contenido de la nota',
  note_form_content_placeholder: 'Introduce el contenido de la nota',
  note_form_submit: 'Guardar nota',
  note_table_btn_edit: 'Editar',
  note_table_btn_delete: 'Eliminar',
  note_action_share: 'Compartir',
  note_action_unshare: 'Dejar de compartir',
  note_action_copy_link: 'Copiar enlace',
  note_action_archive: 'Archivar',
  note_action_restore: 'Restaurar',
  note_action_delete_permanently: 'Eliminar permanentemente',

  about_page_title_one: 'Acerca de',
  about_page_title_two: 'TaskNote App',
  about_page_title_three: 'Tareas y notas',
  about_page_title_four: 'Simplificadas',
  about_page_subtitle: 'Encuentre más información sobre nosotros y la aplicación.',
  about_app_title: 'Acerca de TaskNote',
  about_app_description: `TaskNote es tu aplicación ideal para gestionar
    tareas y notas en un solo lugar. Ya sea que estés organizando tareas diarias
    o tomando notas de reuniones importantes, TaskNote te ayuda a mantenerte
    organizado y productivo.`,
  about_app_features: 'Características',
  about_app_features_one: 'Añade y gestiona tareas y notas de manera rápida',
  about_app_features_two: 'Busca y filtra notas fácilmente',
  about_app_features_three: 'Interfaz intuitiva y limpia',
  about_app_features_four: 'Soporte para tema oscuro y claro con diseño responsivo',
  about_app_features_five: 'Adjuntos de URL para tareas y notas',
  about_app_features_six: 'Sistema de etiquetas con múltiples etiquetas por elemento',
  about_app_features_seven: 'Compartir notas públicamente mediante enlaces públicos',
  about_app_features_eight: 'Barra de herramientas de formato Markdown para edición de texto enriquecido',
  about_app_features_nine: 'Confirmación de correo electrónico requerida para la seguridad de la cuenta',
  about_app_help_title: 'Ayuda & Cómo usar',
  about_app_help_description: `Para empezar, regístrate o inicia sesión,
    y tendrás acceso a tu panel personalizado. Desde allí, podrás crear, 
    editar y eliminar tareas y notas, organizándolas como desees. ¿Necesitas
    ayuda? Consulta la barra lateral para navegación rápida.`,

  about_tech_title: 'Acerca de la Tecnología',
  about_tech_description: `TaskNote fue construido con tecnologías web modernas
    que garantizan velocidad, fiabilidad y seguridad.`,
  about_tech_list_one: 'React 19 con TypeScript para el desarrollo del frontend',
  about_tech_list_two: 'Vite para builds y desarrollo rápidos',
  about_tech_list_three: 'React Router 7 para enrutamiento del lado del cliente',
  about_tech_list_four: 'i18next para soporte de internacionalización',
  about_tech_list_five: 'Bootstrap 5 para diseño y componentes responsivos',
  about_tech_list_six: 'Java y Spring Boot 4.x más GraalVM para el back-end y Cloud Nativo',
  about_tech_list_seven: 'PostgreSQL para la gestión de bases de datos',
  about_tech_list_eight: 'Docker para la contenedorización y despliegue',
  about_tech_list_nine: 'GitHub Actions para CI/CD, pruebas y control de calidad',
  about_tech_list_ten: 'SonarCloud y GitHub QL para chequeos de seguridad y mejoras',

  about_dev_title: 'Acerca del Desarrollador',
  about_dev_description: `¡Hola! Soy Ricardo, el desarrollador de TaskNote. 
    Me apasiona crear aplicaciones que faciliten la vida y ayuden a organizarse.
    Puedes contactarme en `,
  about_dev_description_two: ' para cualquier duda o comentario.',
  about_buy_coffee_one: 'También puedes ',
  about_buy_coffee_link: 'Comprarme un café',

  account_header_my: 'Mi',
  account_header_account: 'Cuenta',
  account_header_update_manage: 'Actualize y Administre, Sus',
  account_header_data: 'Datos',
  account_data_update_header: 'Actualice solo lo necesario. Los campos en blanco no se actualizarán',
  account_form_first_name_label: 'Nombre de pila',
  account_form_first_name_placeholder: 'Su nombre',
  account_form_save: 'Guardar',
  account_form_gravatar_one: 'Si quieres mostrar tu foto, admitimos Gravatar. Visita ',
  account_form_gravatar_two: ' Para registrarte o actualizar tu foto de perfil. Una vez actualizada, espera unos segundos para verla aquí.',
  account_my_account_hello: '¡Hola! Aquí puedes gestionar tus preferencias.',
  account_my_account_logged: 'Has iniciado sesión como: ',
  account_app_lang_title: 'Cambia el idioma del App',
  account_app_lang_description: 'Puedes elegir uno de estos idiomas:',
  account_app_lang_available: 'Idiomas disponíbles',
  account_privacy_little: 'Su Privacidad es Importante',
  account_privacy_subtitle: 'Tú decides cuándo eliminar tus datos',
  account_privacy_text: `Nos comprometemos a proteger su privacidad y a brindarle
    control total sobre sus datos. Puedes solicitar la eliminación completa de su
    cuenta en cualquier momento. Una vez procesada, toda su información personal
    será eliminada permanentemente de nuestros servidores.`,
  account_privacy_delete_btn: 'Borrar todos mis datos',
  account_delete_title: 'Estás a punto de eliminar tu cuenta!',
  account_delete_description: `Esta acción no se puede deshacer. Si realmente desea
    eliminar todos sus datos, escriba su contraseña actual y haga clic en el botón que
    aparece a continuación. Si no es así, cierre este mensaje y sus datos estarán seguros.`,
  account_delete_btn: 'Sí, borra todo',

  footer_my_account: 'Mi Cuenta ',
  sidebar_last_seen: 'Último acceso {{time}}',

  logout: 'Cerrar sesión'
};

export default esTranslations;
