schemaspy.t=pgsql11
schemaspy.host=tasknote-db
schemaspy.port=5432
schemaspy.db=tasknote
schemaspy.u=tasknoteuser
schemaspy.p=default
schemaspy.schemas=tasknote
schemaspy.debug=true
schemaspy.noTablePaging=true
